version: '3.8'

services:

  spring-boot:
    build:
      context: .
      dockerfile: ./spring-boot/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    links:
    - postgres
    - keycloak
    env_file:
    - 'variables.env'
    healthcheck:
      test: curl -f http://localhost:8080/profile || exit 1
      interval: 1m
      timeout: 10s
      retries: 2

  postgres:
    image: postgres:12
    container_name: postgres-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
    - 'variables.env'
    healthcheck:
      test: pg_isready -U postgres
      interval: 1m
      timeout: 10s
      retries: 2

  keycloak-db:
    image: postgres
    container_name: keycloak-db
    volumes:
      - postgres_data:/var/lib/postgresql/data2
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      KEYCLOAK_FRONTEND_URL: http://localhost:8080/auth
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    links:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  pgadmin: